### PR TITLE
Some util extension methods and coroutines.

### PR DESCRIPTION
**Pull request by garcialuigi**

### CODE REVIEW

**Comment by garcialuigi** [comment]
Hi James.
I liked your idea to put some useful things together.
I will provide some things that I believe is useful too.
This ones I just remembered, but I believe I have more.
Are you a professional game developer? Or you are studying yet?
You are very active here on github, I started to follow your projects one week ago.
Very cool.

**Comment by james7132** [comment]
I am by no means a professional game developer. Just a normal CS student with a game dev hobby. 

Thanks man!

**Comment by garcialuigi** [comment]
that means a future game dev :D

**Comment by james7132** [comment]
I'm more of a robotics researcher than a game dev. Game development is more of a hobby of mine than anything else. I have no plans on making money or commercializing any of my projects.

**Pull request merged**
